[phases.setup]
nixPkgs = ["php84", "php84Extensions.gd", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.curl", "php84Extensions.zip", "php84Extensions.bcmath", "php84Extensions.tokenizer", "composer"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction"]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php -S 0.0.0.0:$PORT -t public"